apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ph-ee-connector-tnm
  title: PH TNM Connector
  description: Zeebe connector integrating with TNM Mpamba APIs for mobile money payments and loan repayments
  annotations:
    github.com/project-slug: one-acre-fund/ph-ee-connector-tnm
    backstage.io/kubernetes-id: ph-ee-connector-tnm
    sonarqube.org/project-key: one-acre-fund_ph-ee-connector-tnm
    backstage.io/code-coverage: sonarqube
  tags:
    - java
    - zeebe-connector
    - payment-hub
    - paymenthub
    - tnm
    - mpamba
    - mno
    - mobile-money
  links:
    - url: https://sonarcloud.io/summary/new_code?id=one-acre-fund_ph-ee-connector-tnm
      title: Code Quality Dashboard
      icon: dashboard
    - url: https://ph-web.oneacrefund.org
      title: Production Environment
      icon: globe
    - url: https://elastic.oneacrefund.org/app/apm/services/ph-ee-connector-mno-tnm
      title: Elastic APM Dashboard
      icon: globe
    - url: https://elastic.oneacrefund.org/app/r/s/VHHw2
      title: Application logs
      icon: globe
    - url: https://elastic.oneacrefund.org/app/r/s/CgjiD
      title: Kong Ingress logs
      icon: globe
    - url: https://github.com/one-acre-fund/ph-ee-connector-tnm/blob/main/.github/workflows/build.yaml
      title: Build Pipeline
      icon: build
spec:
  type: worker
  lifecycle: production
  owner: group:one-acre-fund/credits-and-payments
  system: connectors
  consumesApis:
    - zeebe-gateway-grpc-api
  dependsOn:
    - resource:default/zeebe-cluster
